version: '3.3'
services:
  node:
    container_name: api-project-node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - api-project
  mongo:
    container_name: api-project-mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - api-project
networks:
  api-project:
    driver: bridge